name: Build Android APK (EAS)
on:
  workflow_dispatch: {}
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Install deps
        run: npm ci || npm i

      - name: EAS login (using token)
        run: |
          if [ -z "${{ secrets.EAS_TOKEN }}" ]; then
            echo "Missing EAS_TOKEN secret"; exit 1;
          fi
          eas whoami || echo "Continuing with token only"
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Trigger remote APK build
        run: |
          eas build -p android --profile preview --non-interactive --json > build.json
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Extract build URL and download APK
        run: |
          sudo apt-get update && sudo apt-get install -y jq curl
          cat build.json
          BUILD_URL=$(jq -r '.builds[0].artifacts.buildUrl' build.json)
          echo "Build URL: $BUILD_URL"
          curl -L "$BUILD_URL" -o unspoken-preview.apk
          echo "APK_PATH=unspoken-preview.apk" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: unspoken-preview-apk
          path: ${{ env.APK_PATH }}
